#!/usr/bin/env bash

function create_links {
  local dotfiles_repo=$1
  local dotfiles_dest=$2
  local dotfile_src
  local dotfile_dest
  
  mkdir -p "$dotfiles_dest"
  
  for file in $(ls -A $dotfiles_repo); do
    dotfile_src="$dotfiles_repo/$file"
    if [[ "$dotfile_src" == *.nolink ]]; then
      continue
    fi

    dotfile_dest="$dotfiles_dest/$file"
    echo   "linking from $dotfile_src"
    if [[ -h $dotfile_src ]]; then
      dotfile_src=$(readlink -f "$dotfile_src")
      echo "         via $dotfile_src"
    fi
    echo   "          to $dotfile_dest"
    ln -sf -T "$dotfile_src" "$dotfile_dest"
  done
}

create_links "$HOME/dotfiles/home" "$HOME"
create_links "$HOME/dotfiles/config" "$HOME/.config"
create_links "$HOME/dotfiles/bundle" "$HOME/.bundle"
