#!/usr/bin/env bash

function downloadFontsTo(){
  local tempdir
  tempdir="$(mktemp -d)"
  echo "using tempdir $tempdir"
  git clone git@github.com:gabrielelana/awesome-terminal-fonts.git "$tempdir"
  cp $tempdir/build/*.ttf "$1"
  rm -rf "$tempdir"
}

[[ -d $HOME/.fonts ]] || mkdir "$HOME/.fonts" || { echo "faild to create ~/.fonts"; exit 1; }
curl -L https://github.com/googlei18n/noto-emoji/raw/master/fonts/NotoColorEmoji.ttf > home/.fonts/NotoColorEmoji.ttf

downloadFontsTo "home/.fonts"
fc-cache -fv "$HOME/.fonts"
