#!/usr/bin/env bash

set -euo pipefail

declare -A versions=()
versions[apache-maven]=3.5.2
versions[dbeaver]=5.3.1
versions[sts]=3.9.2
versions[openjdk8]=8u191-b12
versions[openjdk9]="jdk-9+181"
versions[openjdk11]="jdk-11.0.1+13"
baseDir=$HOME/programs

#
# $1 = key in versions array
# $2 = download url
# $3 = checksum url (empty/'skip' to skip checksum)
# $4 = target dir name (default = $1)
# $5 = num of components to strip when extracting (default = 1)
#
downloadExctractLink() {
  local name=$1
  local url="$2"
  local urlChecksum="${3:-}"
  local targetDir=$baseDir/${4:-$name}
  local stripComponents=${5:-1}
  local extractDir=$targetDir/$name-${versions[$name]:-$6}
  local filename="$targetDir/${url##*/}"
  local expectedChecksum actualChecksum

  echo "Installing $name ${versions[$name]}"
  echo "  from $url"
  [[ -d "$targetDir" ]] || mkdir -p "$targetDir"
  [[ -f "$filename" ]] || curl -L --fail -o "$filename" "$url" || return 2
  if [[ -n "${urlChecksum}" ]] && [[ "${urlChecksum}" != "skip" ]]; then
    sumprog=${urlChecksum%%:*}
    echo "sumprog: $sumprog"
    urlChecksum=${urlChecksum#*:}
    echo "urlChecksum: $urlChecksum"
    if ! expectedChecksum=$(curl -L --fail --silent "$urlChecksum" | cut -d' ' -f1); then
      echo "Could not fetch checksum"
      return 3
    fi
    echo "expected checksum: $expectedChecksum"
    actualChecksum=$($sumprog < "$filename" | sed -e 's/[ -]//g') || return 4
    if [[ "$expectedChecksum" != "$actualChecksum" ]]; then
      echo "Checksum mismatch ($sumprog)"
      echo "  expected $expectedChecksum"
      echo "       got $actualChecksum"
      return 5
    else
      echo "Checksum OK ($sumprog: $actualChecksum)"
    fi
  else
    echo "Skipping checksum..."
  fi
  
  echo "Extracting ${filename##*/}..."
  [[ -d "$extractDir" ]] || mkdir -p "$extractDir"
  tar xf "$filename" --strip-components "$stripComponents" -C "$extractDir"
  echo "Creating symlink..."
  ln -sfT "$name-${versions[$name]}" "$targetDir/current"
  echo "Done."
}


installMaven() {
  local name=apache-maven
  downloadExctractLink \
    "$name" \
    "https://www.apache.org/dist/maven/maven-3/${versions[$name]}/binaries/apache-maven-${versions[$name]}-bin.tar.gz" \
    "https://www.apache.org/dist/maven/maven-3/${versions[$name]}/binaries/apache-maven-${versions[$name]}-bin.tar.gz.sha1"
}

installDBeaver() {
  local name=dbeaver ini=$baseDir/dbeaver/current/dbeaver.ini
  downloadExctractLink \
    "$name" \
    "https://dbeaver.jkiss.org/files/${versions[$name]}/dbeaver-ce-${versions[$name]}-linux.gtk.x86_64.tar.gz" \
    "sha1sum:https://dbeaver.jkiss.org/files/${versions[$name]}/checksum/dbeaver-ce-${versions[$name]}-linux.gtk.x86_64.tar.gz.sha1"
}

installSTS() {
  local name=sts ini=$baseDir/sts/current/sts-${versions[$name]}.RELEASE/STS.ini
  downloadExctractLink \
    "$name" \
    "http://download.springsource.com/release/STS/${versions[$name]}.RELEASE/dist/e4.7/spring-tool-suite-${versions[$name]}.RELEASE-e4.7.2-linux-gtk-x86_64.tar.gz" \
    "skip"
  echo -e "-vm\n$baseDir/java/current/bin\n$(cat "$ini")" > "$ini"
}

installOpenJDK8() {
  local name=openjdk8
  downloadExctractLink \
    "$name" \
    "https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u192-b12/OpenJDK8U-jdk_x64_linux_hotspot_8u192b12.tar.gz" \
    "sha256sum:https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u192-b12/OpenJDK8U-jdk_x64_linux_hotspot_8u192b12.tar.gz.sha256.txt" \
    "java" \
    2
}

installOpenJDK9() {
  local name=openjdk9
  downloadExctractLink \
    "$name" \
    "https://github.com/AdoptOpenJDK/openjdk9-binaries/releases/download/jdk-9%2B181/OpenJDK9U-jdk_x64_linux_hotspot_9_181.tar.gz" \
    "sha256sum:https://github.com/AdoptOpenJDK/openjdk9-binaries/releases/download/jdk-9%2B181/OpenJDK9U-jdk_x64_linux_hotspot_9_181.tar.gz.sha256.txt" \
    "java" \
    2
}

installOpenJDK11() {
  local name=openjdk11
  downloadExctractLink \
    "$name" \
    "https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.1%2B13/OpenJDK11U-jdk_x64_linux_hotspot_11.0.1_13.tar.gz" \
    "sha256sum:https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.1%2B13/OpenJDK11U-jdk_x64_linux_hotspot_11.0.1_13.tar.gz.sha256.txt" \
    "java" \
    1
}


while [[ -n ${1:-} ]]; do
  case $1 in
    maven)
      installMaven
      ;;
    oracleJDK)
      installJavaOracle
      ;;
    openjdk8)
      installOpenJDK8
      ;;
    openjdk9)
      installOpenJDK9
      ;;
    openjdk11)
      installOpenJDK11
      ;;
    sts)
      installSTS;;
    dbeaver)
      installDBeaver;;
    *)
      echo "Unknown program: $1"
      ;;
  esac
  shift
done


