#!/usr/bin/env bash
set -eu

# peco https://github.com/peco/peco
# fzf  https://github.com/junegunn/fzf
# gitql
# ripgrep https://github.com/BurntSushi/ripgrep
# 
# shell check 
# googler https://github.com/jarun/googler
# exa https://github.com/ogham/exa
# pdsh https://linux.die.net/man/1/pdsh
# 
# hecate https://github.com/evanmiller/hecate
# 
# usql https://github.com/xo/usql
# overmind https://github.com/DarthSim/overmind
# goreman https://github.com/mattn/goreman
# httpstat https://github.com/davecheney/httpstat
# 
# Alacritty https://github.com/jwilm/alacritty

declare -A groups=()
groups[term]="git tig neovim python-neovim shellcheck fzf ripgrep exa alacritty-git tmux xsel"
#groups[i3]="i3-wm polybar rofi"
groups[gnome]="gpaste"
groups[media]="mpv vlc qt4 lollypop"
groups[dropbox]="dropbox nautilus-dropbox"
groups[opt]="peco grv-git"
groups[fonts]="ttf-google-fonts-opinionated-git"
groups[browser]="vivaldi-snapshot vivaldi-snapshot-ffmpeg-codecs"
groups[dev]="docker lxc nodejs npm go ruby-install slack-desktop networkmanager-openconnect meld"

fromAur() {
  local tmpdir
  app=$1
  tmpdir=$(mktemp -d) || { echo "could not create temp dir"; return 1; }
  cd "$tmpdir"
  curl -LO --fail "https://aur.archlinux.org/cgit/aur.git/snapshot/$app.tar.gz"
  tar xf "$app.tar.gz"
  cd "$app"
  makepkg -si --noconfirm
}

develPkgs=($(pacman -Sg base-devel | cut -d' ' -f2))
if ! pacman -Q ${develPkgs[*]} &>/dev/null; then
  echo "Need to install base-devel package group"
  sudo pacman -S --needed --noconfirm base-devel
fi

if ! command -v yaourt > /dev/null; then
  fromAur package-query
  fromAur yaourt
fi

declare -a groupKeys
if [[ "${1:-}" == "all" ]]; then
  groupKeys=(${!groups[@]})
else
  groupKeys=($@)
fi

if [[ ${#groupKeys[@]} -eq 0 ]]; then
  echo "No groups given, use one or more of"
  for key in "${!groups[@]}"; do
    echo "  $key"
    echo "    ${groups[$key]}"
  done
  echo "  all"
  echo "    install all groups"
  exit 1
fi

for key in "${groupKeys[@]}"; do
  pkgs=${groups[$key]}
  echo "Installing packages of group $key"
  yaourt -S --needed --noconfirm $pkgs
done
