-- require('impatient')
require('user.plugins')
require('user.opts')
require('user.keymap')
require('user.colorscheme')
require('user.gitsigns')
require('user.treesitter')
require('user.autopairs')
require('user.comment')
require('user.nvim-tree')
require('user.lualine')
require('user.illuminate')
require('user.lsps')
require('user.cmp')
