# vim: ft=zsh

# if [[ -z "$TMUX" ]] && [[ "$TERM" == "alacritty" ]] && command -v tmux &>/dev/null; then
#   tmux attach || tmux -2
#   exit
# fi

#[[ -n "$TMUX" ]] && export TERM='screen-256color'
[[ -f /etc/profile.d/vte.sh ]] && source /etc/profile.d/vte.sh

# include users local bin dir in path first
[[ -d $HOME/.local/bin ]] && path=($HOME/.local/bin $path)
[[ -d $HOME/bin ]] && path=($HOME/bin $path)
# [[ -d $HOME/.luarocks/bin/ ]] && path=($path $HOME/.luarocks/bin)
[[ -d $HOME/go/bin ]] && path=($path $HOME/go/bin)

ZSH_SOURCE_DIR="$HOME/dotfiles/zsh"
source "$ZSH_SOURCE_DIR/functions.zsh" && sourceIncludeFiles "$ZSH_SOURCE_DIR"

WORDCHARS="*?_-.[]~&;!#$%^(){}<>"
source "$ZSH_SOURCE_DIR/kbd.zsh"

if [[ -f  "$ZSH_SOURCE_DIR/modules.sh" ]]; then
  source "$ZSH_SOURCE_DIR/modules.sh"
  for mname in "${moduleOrder[@]}"; do
    mdir="$ZSH_SOURCE_DIR/modules/$mname"
    typeset -i mloaded=0
    for f in "$mdir/init.zsh" "$mdir/$mname.zsh" "$mdir/$mname.plugin.zsh" "$ZSH_SOURCE_DIR/modules/$mname.init.zsh"; do
      if [[ -f "$f" ]]; then
        source "$f"
        mloaded=1
        break
      fi
    done
    (( mloaded == 0 )) && echo "Don't know how to load module '$mname'"
  done
  unset subtrees
  unset mloaded
  unset moduleOrder
fi

FAST_HIGHLIGHT_STYLES[path]="fg=green"
[[ -f "$HOME/.zshrc.local" ]] && source "$HOME/.zshrc.local"
source "$ZSH_SOURCE_DIR/prompt.zsh"
#[[ -f "$HOME/.config/broot/launcher/bash/br" ]] && source "$HOME/.config/broot/launcher/bash/br"
